name: test-checkout
on:
  push:
    branches:
      - develop
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: check-repo
        uses: actions/checkout@v3
        with:
          repository: josephburling/repo_test_2
          ref: main
