name: test-checkout
on:
  push:
    branches:
      - develop
jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ !env.ACT }}
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout Other
        if: ${{ !env.ACT }}
        id: check-repo
        uses: actions/checkout@v3
        with:
          repository: josephburling/repo_test2
          ref: main
          path: other
          ssh-key: ${{secrets.PRIVATE_REPO_DEPLOY_KEY}}
